version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go get -v -u github.com/chfanghr/librespot/...
workflows:
  version: 2
  build_and_test:
    jobs:
      - build